spring:
  application:
    name: spring-boot-cassandra-playground
  cassandra:
    contact-points: localhost:9042
    local-datacenter: dc1
    keyspace-name: spring_boot_cassandra_playground
    schema-action: none
    connection:
      init-query-timeout: 5s
    request:
      timeout: 5s
  flyway-nc:
    default-schema: ${spring.cassandra.keyspace-name}
